lib/responders/controller_method.rb
In a Rails application using responders, we cannot set
`config.action_controller` configurations in the initializers phase,
because responders loads ActionController too early. This patch fixes
the problem by moving codes into lazy load hook.
=> Lazy load ActionController

responders.gemspec
when an older version is already installed, generated gemspec file gets wrong version (noticed in debian package)
=> use unshift for load path

lib/action_controller/responder.rb, test/action_controller/respond_with_test.rb
Based on #146.
@lucasmazza: i thought it's better to check for `ActionView::Rendering` than for `ActionController::API`, because someone can use API and include the view rendering still. The current logic is depending on the view layer raising a template not found exception (so then it knows to switch to api behavior), so i thought it would be more consistent to handle it similarly when the view layer is not present. Not sure if it makes sense to use API with view rendering readded though, so i'm happy to refactor the code.
=> Fix rendering in Rails 5 API controllers.

lib/generators/rails/templates/api_controller.rb
I've decided to try Rails 5 with a new API-only application. 
During my tests I've found that the current controller generator stumbles with the following error:
```
Could not find "api_controller.rb" in any of your source paths. Your current source paths are:
/Users/vestimir/.gem/ruby/2.3.0/gems/responders-2.1.0/lib/generators/rails/templates
```
So I've added a new template file for API controllers to fix this. By default it renders JSON and skips new and edit actions. 
**The problem**
Whenever I curl the resource I get an empty response, but if I put `render json: @posts`, instead of `respond_with(@posts)` I get proper JSON response. 
Could this be caused by some missing view-related middleware, any clues where to search in the codebase about this?
=> Add Rails 5 API controller template for the controller generator

CHANGELOG.md, README.md, lib/action_controller/respond_with.rb, test/action_controller/verify_request_format_test.rb
You can use `verify_request_format!` as a `before_action` callback to valida
the request mime type before the action is invoked, and prevent any extra wo
if the request format isn't configured for the current action.
Closes #143.
=> Add the `verify_request_format!` method

CHANGELOG.md, README.md, lib/responders/flash_responder.rb, test/responders/flash_responder_test.rb
1. Add support for a more specific controller method, `flash_interpolation_options`,
which can be more intention revealing for developers reading the controller
implementation without having prior knowledge of the Responders API.
2. Avoid merging `nil` onto the existing options Hash, so the controller implementation
doesn't need to worry about returning empty hashes when it can create the
interpolation options (for instance, when the method is called for an `index`
action when you only want ot pass interpolation options to resource specific
actions).
=> Improve `interpolation_options` integration.

CHANGELOG.md, lib/action_controller/respond_with.rb, lib/action_controller/responder.rb, test/action_controller/respond_with_test.rb
Hey guys 👋 , thanks for maintaining the responders gem
- Rails allow to pass a string or a method directly to the `render` method, if it contains a `/` in it's name we consider that the full path needs to be render, otherwise it will fallback to a template matching the action's name https://github.com/rails/rails/blob/4-2-stable/actionview/lib/action_view/rendering.rb#L119-L122
- This PR delates that logic to rails by removing the explicit `action` when rendering a template
Fixes #162
=> Allow rendering a template outside of controller's path:

responders.gemspec
This reduces unneeded redirection from `http://...` to `https://...` when someone visits this gem's homepage via https://rubygems.org/gems/responders.
=> GitHub is HTTPS by default

lib/action_controller/respond_with.rb
While running `memory_profiler` against our app, I noticed `responders` was duplicating some action names:
```
Retained String Report
-----------------------------------
"show"
132  /tmp/bundle/ruby/2.5.0/gems/responders-2.4.1/lib/action_controller/respond_with.rb:40
"index"
126  /tmp/bundle/ruby/2.5.0/gems/responders-2.4.1/lib/action_controller/respond_with.rb:40
```
Rather than to cast all that as strings, we do the inverse, we cast everything as symbols. These are action names, so they're normally a fairly limited set. Interning them shouldn't be a concern.
cc @rafaelfranca
=> Deduplicate action names

README.md
`bob@bob.com` could be an actual email so use a [reserved domain](https://www.iana.org/domains/reserved) instead.
=> Use example domain for email

responders.gemspec
See https://github.com/rubygems/rubygems/pull/2436 and https://github.com/rubygems/rubygems/pull/2798.
=> `rubyforge_project` attribute was removed from rubygems

gemfiles/Gemfile-rails.6.0.x
Because master is now 6.1.0.alpha.
=> Point Rails 6 Gemfile to 6-0-stable

responders.gemspec
So that responders can be easily tested against current rails master (6.1.0.alpha), and it's easier to get early feedback and bug reports.
References https://github.com/plataformatec/responders/commit/6e28cb3db90f1e3edd31e951172e78302c6a2e64#commitcomment-34011176.
=> Allow Rails 6.1 prereleases

README.md
Thanks for this great project!
This PR includes some minor updates the README, mostly stylistic improvements.
* Colors code block with Ruby syntax highlighting
* Fixes spelling error
* Consistently wraps output in code blocks
* Capitalizes MIME to prevent any kind of ambiguity as to what MIME types are
=> Documentation: Minor README improvements

lib/action_controller/respond_with.rb
Just a tiny documentation typo fix. :relaxed:
=> Fix typo in 'respond_with' documentation

CHANGELOG.md, README.md, lib/action_controller/respond_with.rb, lib/action_controller/responder.rb, test/action_controller/respond_with_test.rb
When responding to a non-GET HTML/JS request that had errors on the
resource, responders would not set any status, which means Rails would
default to `200 OK`. This has been long working like this but also a
long discussion in responders to change that behavior, to be more inline
with how other types of requests (like JSON/XML) handle responses by
setting the HTTP status to 422 Unprocessable Entity when responding with
an error.
More recently with the Turbo/Hotwire library, they've added support to
render form responses as errors with 4xx statuses [1], so it makes even
more sense for responders to make the move here.
This change now makes responders use the 422 Unprocessable Entity status
in such cases when the resource has errors, and should work more out of
the box with Turbo/Hotwire. …
=> Respond with 422 Unprocessable Entity for non-GET HTML/JS requests with errors

lib/action_controller/responder.rb, lib/responders.rb, test/action_controller/respond_with_test.rb
This PR adds system tests for Responders with a dummy Rails app that's using Hotwire.
Hotwire currently handles non-GET requests slightly differently if you submit a form with a `_method` or if you have a link using `data-turbo-method`. This adds a test for both of those cases to confirm that the redirect is handled correctly using a 303 to safely handle both cases.
With a 302, the `data-turbo-method` will actually forward the request method to the redirect URL. This results in a `DELETE /posts/1` redirecting to `DELETE /posts`. A 303 will change the redirect to a `GET /posts` correctly.
**Why is this necessary?**
`button_to` will generate a form with `method="post"` and `_method="delete"` as a hidden field. It sends a POST request to Rails, which then gets handled like a `DELETE`. …
=> System tests with Hotwire

lib/responders.rb
`redirect_status` was accidentally referring to the Rails app config instead of the Responders config.
This fixes #235
cc @rafaelfranca
=> Fixes redirect_status config

CHANGELOG.md, README.md, lib/action_controller/respond_with.rb, lib/action_controller/responder.rb, lib/generators/responders/install_generator.rb, lib/responders.rb, test/action_controller/respond_with_test.rb
This essentially makes the previous change merged via https://github.com/heartcombo/responders/pull/223 configurable,
so that we can keep the current behavior on existing apps, returning `200 OK` even for errors, while changing the generator for new apps to be configured with `422 Unprocessable Entity`, making them work better with Hotwire/Turbo installations out of the box.
Please note that these defaults are likely to be swapped in a future major version of Responders.
=> Make error status for HTML/JS responses fully configurable

README.md
Found by `typos --format brief`
=> Fix typo, compatibilty -> compatibility
